spring:
  datasource:
    url: jdbc:mysql://:3306/login?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: bobomysql
    driver-class-name: com.mysql.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update


server:
  port: 81
